version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Specify the Node.js version you want to use
    commands:
      - npm install

  build:
    commands:
      - npm run build  # Replace this with the build command for your Node.js application

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - node_modules
